### ISSUE TITLE
[FR] Match icons using icon parameter

### ISSUE THREAD

**Issue by darkelectron** [darkelectron/pyweather#2]

**Comment by Sohail4625** [comment]
@darkelectron Can you provide a description of the problem

**Comment by darkelectron** [comment]
API Response: https://openweathermap.org/weather-conditions

In the config under `[ICONS]`, instead of using weather "description" (as in the API response), it might be better to use "icon" since a lot of the icons repeat anyway.

---

This would mean the config would look like this.

```
[ICONS]
01d =
01n =
02d = 
02n =
...
```

Edit: @Sohail4625

**Comment by darkelectron** [comment]
As of 0.2.0
